spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5433/samurai
    username: samurai
    password: password

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  docker:
    compose:
      file: src/main/docker/compose.yml
      enabled: true
      lifecycle-management: start_only

competition:
  scheduleStartTime: "0 0 0 * * MON"

pagination:
  defaultPageSize: 50
  defaultPage: 0

server:
  port: 8080